{"name": "test_login_failure_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <com.python.pytest_test1.test_feature_story.TestLogin object at 0x0000016CB7F67130>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure_c(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"输入密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>            assert '1' == 1\nE            AssertionError: assert '1' == 1\n\ntest_feature_story.py:32: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1613575575381, "stop": 1613575575381}, {"name": "输入密码", "status": "passed", "start": 1613575575381, "stop": 1613575575381}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\PythonData\\com\\python\\pytest_test1\\test_feature_story.py\", line 32, in test_login_failure_c\n    assert '1' == 1\n"}, "start": 1613575575381, "stop": 1613575575381}], "attachments": [{"name": "stdout", "source": "b06bdb5e-c6e5-4848-a477-2d5a642e8921-attachment.txt", "type": "text/plain"}], "start": 1613575575381, "stop": 1613575575381, "uuid": "939cd10b-2624-4fe5-b1c5-6870ff3a2ebb", "historyId": "9ad5fff39a351e5d2c61624bf70a5349", "testCaseId": "d631a7e1730c30e5ade5dd1bebc3b9ae", "fullName": "test_feature_story.TestLogin#test_login_failure_c", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-39CMD4K"}, {"name": "thread", "value": "37756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}